{{- if .Values.agent.enabled }}
{{- if not .Values.wazuh.enabled }}
{{- if not .Values.agent.apiCred.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: {{ .Release.Namespace }}
data:
  API_USERNAME: {{ .Values.agent.apiCred.username | default (randAlphaNum 10) | b64enc }}
  API_PASSWORD: {{ .Values.agent.apiCred.password | default (randAlphaNum 16) | b64enc }}
{{- end }}
{{- end }}
{{- end }}