{{- if .Values.wazuh.master.enabled }}
{{- if .Values.wazuh.master.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-master
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "wazuh.fullname" . }}-manager
      node-type: master
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        {{- range .Values.wazuh.master.service.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
      from:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.fullname" . }}-dashboard
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.fullname" . }}-agent
              node-type: agent
    - ports:
        - protocol: TCP
          port: {{ .Values.wazuh.service.port }}
      from:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.fullname" . }}-manager
              node-type: worker
  egress:
    # Wazuh CTI (Cyber Threat Intelligence)
    - ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: {{ .Values.indexer.service.httpPort }}
      to:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.indexer.fullname" . }}-indexer
    - ports:
        - protocol: UDP
          port: 53
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
{{- end -}}
{{- end }}