{{- if .Values.certificates.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "wazuh.fullname" . }}-root-ca
  namespace: {{ .Release.Namespace }}  
spec:
  isCA: true
  secretName: {{ include "wazuh.fullname" . }}-root-secret
  commonName: {{ include "wazuh.fullname" . }}-root-ca
  subject:
    organizations:
      - {{ .Values.certificates.subject.organization }}
    countries:
      - {{ .Values.certificates.subject.country }}
    localities:
      - {{ .Values.certificates.subject.locality }}
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 87600h # 3650d
  issuerRef:
    name: {{ .Values.certificates.issuer.name | default (printf "%s-selfsigned-issuer" (include "wazuh.fullname" .)) }}
    {{- if eq .Values.certificates.issuer.type "ClusterIssuer" }}
    kind: ClusterIssuer
    {{- end }}
{{- end }}