# https://cert-manager.io/docs/configuration/selfsigned/
{{- if .Values.certificates.enabled }}
{{- if not .Values.certificates.issuer.name }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end -}}
{{- end }}