{{- if .Values.indexer.deployment.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wazuh.indexer.fullname" . }}-indexer
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: indexer-StatefulSet
    app: {{ include "wazuh.indexer.fullname" . }}-svc
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: indexer-StatefulSet
spec:
  serviceName: {{ include "appIdentifier" .Values.identifier }}
  replicas: {{ .Values.indexer.images.replicaCount }}
  updateStrategy:
    type: {{ .Values.indexer.images.updateStrategy }}
  selector:
    matchLabels:
{{ include "labels" $ | indent 6 }}
      app: {{ include "wazuh.indexer.fullname" . }}
      role: master
  serviceName: {{ include "appIdentifier" .Values.identifier }}-indexer-nodes
  template:
    metadata:
      labels:
{{ include "labels" $ | indent 8 }}
        appComponent: indexer-StatefulSet
        app: {{ include "wazuh.indexer.fullname" . }}
        role: master
      annotations:
{{ include "annotations" $ | indent 8 }}
        appComponent: indexer-StatefulSet
    spec:
      volumes:
      - name: indexer-certs
        secret:
          secretName: indexer-certs
      - configMap:
          name: {{ template "wazuh.indexer.fullname" . }}-config
        name: indexer-conf
      initContainers:
        - command:
          - sh
          - -c
          - chown -R 1000:1000 /var/lib/wazuh-indexer
          image: busybox
          name: volume-mount-hack
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/lib/wazuh-indexer
              name: wazuh-indexer
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: busybox
          name: increase-the-vm-max-map-count
          securityContext:
            privileged: true
      containers:
        - name: wazuh-indexer
          image: "{{ .Values.indexer.images.repository }}:{{ .Values.indexer.images.tag }}"
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.indexer.env.OPENSEARCH_JAVA_OPTS | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.indexer.env.CLUSTER_NAME | quote }}
            - name: NETWORK_HOST
              value: {{ .Values.indexer.env.NETWORK_HOST | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: {{ .Values.indexer.env.DISCOVERY_SERVICE | quote }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: {{ .Values.indexer.env.DISABLE_INSTALL_DEMO_CONFIG | quote }}
          resources:
{{ toYaml .Values.indexer.images.resources | indent 12 }}
          volumeMounts:
            - mountPath: /var/lib/wazuh-indexer
              name: wazuh-indexer
            - mountPath: /usr/share/wazuh-indexer/certs/node-key.pem
              name: indexer-certs
              readOnly: true
              subPath: node-key.pem
            - mountPath: /usr/share/wazuh-indexer/certs/node.pem
              name: indexer-certs
              readOnly: true
              subPath: node.pem
            - mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              name: indexer-certs
              readOnly: true
              subPath: root-ca.pem
            - mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              name: indexer-certs
              readOnly: true
              subPath: admin.pem
            - mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              name: indexer-certs
              readOnly: true
              subPath: admin-key.pem
            - mountPath: /usr/share/wazuh-indexer/opensearch.yml
              name: indexer-conf
              readOnly: true
              subPath: opensearch.yml
            - mountPath: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
              name: indexer-conf
              readOnly: true
              subPath: internal_users.yml
            - mountPath: /usr/share/wazuh-indexer/opensearch-security/roles_mapping.yml
              name: indexer-conf
              readOnly: true
              subPath: roles_mapping.yml
            - mountPath: /usr/share/wazuh-indexer/opensearch-security/roles.yml
              name: indexer-conf
              readOnly: true
              subPath: roles.yml
            - mountPath: /usr/share/wazuh-indexer/opensearch-security/config.yml
              name: indexer-conf
              readOnly: true
              subPath: config.yml
            {{- if .Values.indexer.FederationMetadata }}
            - mountPath: /usr/share/wazuh-indexer/opensearch-security/FederationMetadata.xml
              name: indexer-conf
              readOnly: true
              subPath: FederationMetadata.xml
            {{- end }}
          ports:
            - containerPort: 9200
              name: indexer-rest
            - containerPort: 9300
              name: indexer-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.indexer.storageSize }}
        storageClassName: {{ .Values.indexer.storageClassName }}
{{- end -}}
