{{- if .Values.wazuh.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  script.sh: |-
    #/bin/sh
    # Updates each workers config to fix hostname
    cp /ossec.conf /wazuh-config-mount/etc/ossec.conf
    node_index=${HOSTNAME##*-}
    sed -i "s/___INDEX___/$node_index/g" /wazuh-config-mount/etc/ossec.conf
  master.conf: |
    {{- tpl .Values.wazuh.master.conf . | nindent 4 }}
  worker.conf: |
    {{- tpl .Values.wazuh.worker.conf . | nindent 4 }}
  local_decoder.xml: | 
    {{- tpl .Values.wazuh.localDecoder . | nindent 4 }}
  local_rules.xml: | 
    {{- tpl .Values.wazuh.localRules . | nindent 4 }}
  internal_options.conf: | 
    {{- tpl .Values.wazuh.internalOptions . | nindent 4 }}
{{- range .Values.wazuh.agentGroupConf }}
  {{ .name }}-agent.conf: | 
    {{- .agent | nindent 4 }} 
{{- end }}
{{- end }}