{{- if and .Values.indexer.enabled .Values.indexer.snapshot.enabled (not .Values.indexer.snapshot.fs.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wazuh.indexer.fullname" . }}-indexer-snapshots
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.indexer.fullname" . }}-indexer
spec:
  accessModes:
    {{- toYaml .Values.indexer.snapshot.fs.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.indexer.snapshot.fs.storageSize }}
  {{- with .Values.indexer.snapshot.fs.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
